version: "3.7"
services:
  web:
    build: .
    depends_on:
      - db
    ports:
      - 8000:80
    env_file:
      - var.env
    volumes:
      - ../data/:/var/www/html/

  db:
    image: mariadb
    env_file:
      - var.env
    volumes:
      - ../db:/var/lib/mysql

